---

- name: All hosts
  hosts: all
  roles:
    - { role: common, tags: common }

- name: Rainbow
  hosts: rainbow
  roles:
    - { role: lan, tags: lan }
    - { role: unifi, tags: unifi }
    - { role: ups, tags: ups }
    - { role: media, tags: media }

- name: Gateway
  hosts: vpn
  roles:
    - { role: vpn, tags: vpn }
